### ISSUE TITLE
main_evaluate.py 실행 시 value error 발생 

### ISSUE THREAD

**Issue by techzzt** [PeterKim1/paper_code_review#1]
main_evaluate 실행시 utils.py 부분에서 return np.transpose(x, [0, 3, 1, 2])에 대해 valueError가 발생합니다

**Comment by PeterKim1** [comment]
안녕하세요? 혹시 https://github.com/PeterKim1/paper_code_review/blob/master/10.%20Patch%20SVDD/codes/utils.py#L136 
해당 코드에서 문제가 발생하셨나요? 

가능하면 에러가 발생한 화면을 캡처해주시면 감사하겠습니다.

**Comment by techzzt** [comment]
main_train.py를 실행하는 과정에서 error가 발생했고 위의 첨부해주신 링크에 있는 코드에서 에러가 발생했습니다. 발생한 에러를 첨부합니다. 감사합니다. 

![image](https://user-images.githubusercontent.com/49440852/162124245-55dcabc2-bb41-440f-ba7e-b3ad0c85a7c3.png)

**Comment by PeterKim1** [comment]
일단 제가 techzzt님의 환경에서 코드를 run 할 수 없으므로, 예상되는 원인에 대한 해결책을 제시해드리겠습니다.

첫 번째 줄에 RuntimeWarning: Mean of empty slice. 라고 적혀있고 mean = images.astype(np.float32).mean(axis=0) 코드에서 에러가 난 것으로 보입니다.

말그대로 empty(빈) 값에 대해서 Mean을 시행했을 때 발생할 수 있는 에러인데, 제가 예상하기에는 images 자체가 아예 빈 데이터일 가능성이 있습니다. 즉, 데이터 경로 이슈일 가능성이 있습니다.

이 부분에 대해서 체크해주시면 감사하겠습니다.
