### ISSUE TITLE
training time 문의 드립니다.

### ISSUE THREAD

**Issue by DeepHM** [PeterKim1/paper_code_review#2]
안녕하세요. 
논문 리뷰 및 코드 리뷰 잘 보았습니다 :)

혹시 patch svdd training에서, 
MVTec data의 bottle 학습 한번 돌려보았는데,
성능 평가 체크 코드를 제외하여도 학습만 1에폭에 40분가량이 걸리는데
혹시 이게 정상적인 시간일까요? 얼마나 걸리셨는지 대충 기억나실까요?

**Comment by PeterKim1** [comment]
안녕하세요 반갑습니다.

해당 코드는 제가 석사과정일 때 돌렸던 코드들이라 개발환경이나 도커 컨테이너등이 남아있지는 않아서 동일 컨디션 하에서 코드를 돌릴 수는 없는 상황입니다.

다만, 제가 판단하기로는 https://github.com/PeterKim1/paper_code_review/blob/master/10.%20Patch%20SVDD/README.md 해당 readme를 보시면 아래에 loss graph를 남겨뒀는데, tensorboard에 찍힌 것을 보았을 때 300에폭에 약 2시간정도 걸린 것으로 보입니다.

DeepHM님의 환경 셋팅 상황은 자세히 모르지만 Pytorch에서 gpu를 인식하지 못해서 cpu로 돌아간다거나 하는 이슈가 발생할 수 있으니 pytorch가 gpu를 잡는지 확인해보시는 것이 좋을 것 같습니다.

**Comment by DeepHM** [comment]
아 제가 착각했습니다 ㅎㅎ 감사합니다!
